### ISSUE TITLE
Support for private nuget feeds

### ISSUE THREAD

**Issue by NielsPilgaard** [ThomasArdal/NuPU#6]
Hi there 👋 

It would be very helpful to me if NuPu was able to determine when a nuget from a feed that is not nuget.org has newer versions, would you perhaps consider looking into that? 🤞

**Comment by ThomasArdal** [comment]
Hi Niels 👋

It should iterate over all available sources: https://github.com/ThomasArdal/NuPU/blob/main/src/NuPU/UpdateCommand.cs#L45

Do you have all the sources your project is dependent of in a `nuget.config` file or somewhere else?

**Comment by NielsPilgaard** [comment]
Yup, I have them in my NuGet.Config in AppData:
https://gist.github.com/NielsPilgaard/0584c61f715b5421ac4d6352f316a972

It just says up to date, even though there are newer versions available.

I've also tried moving the `NuGet.Config` to the solution I'm analyzing, no luck either unfortunately.

**Comment by ThomasArdal** [comment]
I just tried creating a custom NuGet feed and adding a package to that. NuPU detects the new version. I guess your feed requires authentication?

**Comment by NielsPilgaard** [comment]
Hmm yes, I was hoping to be prompted for credentials if they were required by NuPu, my bad!

Adding credentials to my nuget.config did the trick, thank you!

Could you perhaps log an error when attempting to access a feed that requires auth you don't have?

I use Azure Artifact Credentials Provider, so I haven't needed to set credentials in my nuget config before 😅

**Comment by ThomasArdal** [comment]
The tool runs over each source and tries to pull updates from the sources that are already authenticated. Adding the credentials in the config is one option.

It could actually catch the 401 and prompt for username and password since the `NuGet.Protocol` package does support authentication. This would require the tool to ask for a username and password on the command line in a home-brewed manner, though. I think I would prefer an approach similar to what `--interactive` is doing in `dotnet.exe`. Ideally showing a popup asking for the credentials or something. I don't know the `NuGet.Protocol` package enough there.

**Comment by NielsPilgaard** [comment]
I'd also prefer something like --interactive, but a simple log would be very helpful as well, if actually authenticating is out of scope.

**Comment by ThomasArdal** [comment]
There's a new version available here soon: https://www.nuget.org/packages/NuPU/1.0.32

I have tried playing with an `--interactive` flag on the command line. It's using this down below:

```csharp
DefaultCredentialServiceUtility.SetupDefaultCredentialService(new NullLogger(), !updateCommandSettings.Interactive);
```

TBH, I don't know exactly what this does but I see all of the other NuGet tools are somewhat touching on this code.

The new version also removes any unauthenticated feeds from the list of sources to check and outputs a warning. This seriously speed up checking each package when there's an unauthenticated source in the list of enabled sources.

**Comment by NielsPilgaard** [comment]
The `--interactive` flag didn't seem to do anything, but the added logging works on my end too, thank you 👍
