### ISSUE TITLE
Add support for `Directory.Packages.props`?

### ISSUE THREAD

**Issue by GZTimeWalker** [ThomasArdal/NuPU#7]
I managed my packages with `Directory.Packages.props`, like https://github.com/GZTimeWalker/GZCTF/blob/develop/src/Directory.Packages.props

But nupu will got `Skipping Microsoft.Extensions.Options because of unknown version` as the csproj file has no version, for example: `<PackageReference Include="Microsoft.Extensions.Options"/>`

**Comment by ThomasArdal** [comment]
That's a good point. Since the `csproj` file doesn't reference the `Directory.Packages.props` file, do you have an idea to how to support this? The code is currently based on finding `*.csproj` files and loading them with `XDocument`. So, there's no code currently that knows about the `csproj` format, other than the commands I shoot at it. The code could start to look for a `Directory.Packages.props` file in the directory specified on the command line. That would require you to launch NuPU in `src` directory. Not sure if that is ideal. Another solution could be to backtrack directories from each `csproj` file to see if there's a `props` file anywhere up the chain.

**Comment by GZTimeWalker** [comment]
Maybe check this manual for more details: https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management?

**Comment by ThomasArdal** [comment]
[Fixed](https://github.com/ThomasArdal/NuPU/commit/7eaf01ab860d1e25f2b287535e7a8737a680513d). Would be awesome if you could try it out as soon as the new version is on NuGet.

**Comment by GZTimeWalker** [comment]
so fast!

**Comment by ThomasArdal** [comment]
Ah wait. There's an error when updating. Looking at that now.

**Comment by ThomasArdal** [comment]
Maybe you have some input. I have tried creating a project with centralized package management. But I keep getting this error when compiling:

```
NU1008	Projects that use central package version management should not define the version on the PackageReference items but on the PackageVersion items: AWSSDK.SimpleEmail.
```

I tried to do like you. Create `Directory.Packages.props` file in the root:

```xml
<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AWSSDK.SimpleEmail" Version="3.7.401.23" />
  </ItemGroup>
</Project>
```

And in each of my `csproj` files I add this:

```xml
<ItemGroup>
  <PackageReference Include="AWSSDK.SimpleEmail" />
</ItemGroup>
```

I also get this warning:

```
NU1504	Duplicate 'PackageReference' items found. Remove the duplicate items or use the Update functionality to ensure a consistent restore behavior. The duplicate 'PackageReference' items are: AWSSDK.SimpleEmail 3.7.401.23, AWSSDK.SimpleEmail
```

**Comment by GZTimeWalker** [comment]
in csproj, it is `PackageReference` and in the props, it is `PackageVersion`, I think that's the point.

**Comment by ThomasArdal** [comment]
I just realized that 🤦🏼‍♂️ Thanks!

**Comment by ThomasArdal** [comment]
Try this version: https://www.nuget.org/packages/NuPU/1.0.45 😄

**Comment by GZTimeWalker** [comment]
> Try this version: https://www.nuget.org/packages/NuPU/1.0.45 😄 

I'll try a few hours later

**Comment by ThomasArdal** [comment]
BTW, there's an improved version here: https://www.nuget.org/packages/NuPU/1.0.46 (you will get that anyway unless you update to a specific version)

**Comment by GZTimeWalker** [comment]
It works well for me and looks good.

Another suggestion would be to default `--includeprerelease` to false, which may be more generic.

**Comment by ThomasArdal** [comment]
It's good to hear that everything works as expected. I want to keep including prereleases since I like to have the option to upgrade to one as a default.

Thank you for submitting this issue, closing it now.
